news/urls.py
from django.urls import path

from .views import (
    index,
    RedactorListView,
    RedactorDetailView,
    TopicListView,
    NewspaperListView,
    NewspaperDetailView, RedactorUpdateView, RedactorDeleteView,
    RedactorCreateView, NewspaperUpdateView,
    NewspaperDeleteView, NewspaperCreateView, TopicUpdateView,
    TopicDeleteView, TopicCreateView, RemoveRedactorView,
    AssignRedactorView, SignupView, UserLoginView, logout_view,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "redactor/",
        RedactorListView.as_view(),
        name="redactor-list",
    ),
    path(
        "redactor/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail",
    ),
    path(
        "redactor/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactor/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "redactor/create",
        RedactorCreateView.as_view(),
        name="redactor-create",
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "topic/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topic/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topic/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "topic/create/",
        TopicCreateView.as_view(),
        name="topic-create"
    ),
    path(
        "newspapers/remove_redactor/",
        RemoveRedactorView.as_view(),
        name="remove-redactor"
    ),
    path(
        "newspaper/assign_redactor",
        AssignRedactorView.as_view(),
        name="assign-redactor"
    ),
    path(
        "signup/",
        SignupView.as_view(),
        name="signup"
    ),
    path(
        "accounts/login/",
        UserLoginView.as_view(),
        name="login"
    ),
    path(
        "accounts/logout/",
        logout_view,
        name="logout"
    ),

]

app_name = "news"

newspaper_agency_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls', namespace='news')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<footer class="footer py-2 mt-auto">
  <div class="container z-index-1 position-relative">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <p class="text-sm text-dark opacity-8 mb-0">
          &copy; Marharyta Marchenko
        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
{% load static %}
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
        class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3"
            href="/" rel="tooltip" data-placement="bottom">
            Newspaper Agency
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
            data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                  href="javascript:;" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                  Pages
                  <img src="{% static 'img/down-arrow-dark.svg' %}" alt="down-arrow" class="arrow ms-1">
                </a>
                <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
                     aria-labelledby="dropdownMenuPages">
                  <div class="d-none d-lg-block">
                    <div 
                        class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center px-0">
                      <div class="d-inline-block">
                        
                      </div>
                    </div>
                  </div>
                  
                  
                  

                    <a href="{% url 'news:newspaper-list' %}" class="dropdown-item border-radius-md">
                      <span class="ps-3">Newspapers</span>
                    </a>
                    <a href="{% url 'news:redactor-list' %}" class="dropdown-item border-radius-md">
                      <span class="ps-3">Redactors</span>
                    </a>
                    <a href="{% url 'news:topic-list' %}" class="dropdown-item border-radius-md">
                      <span class="ps-3">Topics</span>
                    </a>
              </li>

              {% if request.user.is_authenticated %}
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2"
                  href="{% url 'logout' %}">
                  <i class="fa fa-sign-out me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" title="Logout">Logout</p>
                </a>
              </li>
                <li class="nav-item">
                <a class="nav-link nav-link-icon me-2" href="https://github.com/March1205" target="_blank">
                  <i class="fa fa-github me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="GitHub">GitHub</p>
                </a>
              </li>
              {% else %}
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2"
                  href="{% url 'login' %}">
                  <i class="fa fa-sign-in me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" title="Login">Login</p>
                </a>
              </li>
                <li class="nav-item">
                <a class="nav-link nav-link-icon me-2" href="https://github.com/March1205" target="_blank">
                  <i class="fa fa-github me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="GitHub">GitHub</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <section class="py-1">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-4 mx-auto">
          <ul class="pagination pagination-primary m-2">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}" aria-label="Previous">
                  <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
                </a>
              </li>
            {% endif %}

            {% for num in paginator.page_range %}
              {% if page_obj.number == num %}
                <li class="page-item active">
                  <a class="page-link" href="javascript:;">{{ num }}</a>
                </li>
              {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                  <a class="page-link" href="?{% query_transform request page=num %}">{{ num }}</a>
                </li>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}" aria-label="Next">
                  <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endif %}

templates/includes/scripts.html
  {% load static %}
  
<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>
  
<script>
    document.addEventListener('DOMContentLoaded', function() {
      const readMore = document.getElementById('read-more');
      const readLess = document.getElementById('read-less');
      const shortContent = document.getElementById('short-content');
      const fullContent = document.getElementById('full-content');

      readMore.addEventListener('click', function(event) {
        event.preventDefault();
        shortContent.style.display = 'none';
        fullContent.style.display = 'block';
      });

      readLess.addEventListener('click', function(event) {
        event.preventDefault();
        shortContent.style.display = 'block';
        fullContent.style.display = 'none';
      });
    });
  </script>  